# Generated by Django 4.1.4 on 2023-07-14 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutproducts',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
