# Generated by Django 4.1.4 on 2023-07-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_checkoutproducts_color_remove_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutproducts',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
